### ISSUE TITLE
#### Format Todo List

### ISSUE THREAD

**Issue by redelste** [redelste/react-flask-todo#13]
- [x] Need to add CSS
- [x] Create Card Components
- [x] Modify layout of inputs. 
- [x] Edit API to separate database calls from endpoints. (Separate model from controller)
